/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wxdwmicqfhcyejkhooub"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZHdtaWNxZmhjeWVqa2hvb3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1MjMxOTYsImV4cCI6MjA5NTA5OTE5Nn0.Y-cWO7H8YDdrTLv9TsDE1MPRd17gzzE7_bzZ-OXF7ZY"